###############################################################################
# This is an ansible playbook for deploying RPMs onto various servers on the
# HPC cluster at DCCN.
#
# use command:
#
#     $ ansible-playbook ansible.yml -K
#
###############################################################################
- name: set version number
  gather_facts: false
  hosts:
    - pbs_mom
    - mentat
    - mgt
  vars_prompt:
    - name: rel_version
      prompt: RPM version to deply
      default: 0.5.0-1.el7.x86_64
      private: no
  tasks:
    - set_fact:
        release: "{{rel_version}}"

- hosts: pbs_mom:mentat:mgt
  gather_facts: false
  become: yes
  tasks:
    - name: check RPM file on nodes
      stat:
        path: /mnt/install/kickstart-7/miscpkgs/torque-helper/hpc-utility-{{ release | mandatory }}.rpm
      register: rpmfile
    - name: fail on RPM file not available
      fail:
        msg: "rpm not found: /mnt/install/kickstart-7/miscpkgs/torque-helper/hpc-utility-{{ release | mandatory }}.rpm"
      when: rpmfile.stat.exists == False
    #- debug: var=ls.stdout_lines
    - name: install/update hpc-utility package
      register: yum
      yum:
        name: /mnt/install/kickstart-7/miscpkgs/torque-helper/hpc-utility-{{ release | mandatory }}.rpm
        state: present
    #- debug: var=yum.results